<a href="https://colab.research.google.com/github/elpinchepastel/IA/blob/master/Tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensor**

---

Keras usa un array multidimensional de NumPy como estructura básica de datos, y llama a esta estructura de datos «tensor». De manera resumida podríamos decir que un tensor tiene tres atributos principales: número de ejes, forma y tipo de datos. Veamos cada uno de ellos:



*   Número de ejes (rank): a un tensor que contiene un solo número lo llamaremos scalar (o tensor 0-dimensional, o tensor 0D). Un array de números lo llamamos vector, o tensor 1D. Un array de vectores será una matriz (matrix), o tensor 2D. Si empaquetamos esta matriz en un nuevo array, obtenemos un tensor 3D, que podemos interpretar visualmente como un cubo de números. Empaquetando un tensor 3D en un array, podemos crear un tensor 4D, y así sucesivamente. En la librería NumPy de Python esto se llama ndim del tensor.

*   Forma: se trata de una tupla de enteros que describen cuántas dimensiones tiene el tensor en cada eje. En la librería NumPy este atributo se llama shape. Un vector tiene un shape con un único elemento, por ejemplo «(5)», mientras que un escalar tiene un shape vacío «( )».

*   Tipo de datos: este atributo indica el tipo de datos que contiene el tensor, que pueden ser por ejemplo uint8, float32, float64, etc. En raras ocasiones tenemos, en nuestro contexto, tensores de tipo char (nunca string). En la librería NumPy este atributo se llama dtype.

In [1]:
# Escalar o tensor 0D:

import numpy as np

x = np.array(8)
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:  8
x ndim:  0
x shape: ()
x size:  1
x dtype:  int64


In [2]:
x = np.array([2.3 , 4.2 , 3.3, 1.8])
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:  [2.3 4.2 3.3 1.8]
x ndim:  1
x shape: (4,)
x size:  4
x dtype:  float64


In [3]:
# Matrix o tensor 2D:

x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("x:\n", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
x ndim:  2
x shape: (3, 3)
x size:  9
x dtype:  int64


In [4]:
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("x:\n", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim:  3
x shape: (2, 2, 2)
x size:  8
x dtype:  int64


In [6]:
# Creación rapida de tensores

print("np.zeros((3,3)):\n", np.zeros((3,3)))
print("np.ones((3,3)):\n", np.ones((3,3)))
print("np.eye((3)): (identity matrix)\n", np.eye((3)))
print("np.random.random((3,3)):\n", np.random.random((3,3)))

np.zeros((3,3)):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
np.ones((3,3)):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
np.eye((3)): (identity matrix)
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
np.random.random((3,3)):
 [[0.83500954 0.64831318 0.24731839]
 [0.97791918 0.10239127 0.37496564]
 [0.43084474 0.04992379 0.02150874]]
